import type { EnemyDef, EnemyKind } from './types'

export const ENEMIES: Record<EnemyKind, EnemyDef> = {
  lemurian: {
    kind: 'lemurian',
    name: 'Lemurian',
    color: '#7a3b24',
    hp: 55,
    damage: 10,
    speed: 3.2,
    radius: 0.55,
    height: 1.6,
    attackRange: 1.6,
    attackCooldown: 1.1,
    xpValue: 10,
    goldValue: 2,
    credits: 10,
  },
  beetle: {
    kind: 'beetle',
    name: 'Beetle',
    color: '#3a2a1a',
    hp: 35,
    damage: 7,
    speed: 2.6,
    radius: 0.45,
    height: 0.9,
    attackRange: 1.2,
    attackCooldown: 1.0,
    xpValue: 7,
    goldValue: 1,
    credits: 6,
  },
  wisp: {
    kind: 'wisp',
    name: 'Lesser Wisp',
    color: '#c96bff',
    hp: 30,
    damage: 12,
    speed: 2.4,
    radius: 0.4,
    height: 0.8,
    attackRange: 12, // ranged
    attackCooldown: 2.2,
    xpValue: 9,
    goldValue: 2,
    credits: 8,
  },
  stone_titan: {
    kind: 'stone_titan',
    name: 'Stone Titan',
    color: '#6d6d72',
    hp: 1400,
    damage: 40,
    speed: 2.0,
    radius: 1.8,
    height: 4.8,
    attackRange: 2.8,
    attackCooldown: 2.0,
    xpValue: 250,
    goldValue: 40,
    credits: 120,
    isBoss: true,
  },
}
